mailServer:
  host: smtp.gmail.com
  port: 587
  email: ltahemlet@gmail.com
  password: nlnj bnsp phzd xymc
  protocol: smtp
  isSSL: false

frontend:
  base-endpoint: http://localhost:5173
backend:
  base-endpoint: http://localhost:8080